# Generated by Django 5.2.7 on 2026-01-19 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Birth_date',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('date_of_incorporation', models.DateField()),
                ('country_of_incorporation', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
