# Generated by Django 6.0.1 on 2026-01-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_birth_date_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
