# Generated by Django 6.0.1 on 2026-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_goldvault_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_accepted_tc',
            field=models.BooleanField(default=False),
        ),
    ]
