# Generated by Django 6.0.1 on 2026-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_sippreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldvault',
            name='purchased_coins_grams',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
